language: node_js

services:
  - couchdb

node_js:
  - "0.10"
  - "0.8"

before_script:
  - npm install -g grunt-cli

after_success:
  - mocha -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js